import {useMemo,useState} from 'react';
import {AlertTriangle, BrainCircuit, FileSearch, Gauge, Lock, Menu, Mic2, ShieldCheck, Users, Volume2, VolumeX, X, Play, ArrowRight, Eye} from 'lucide-react';
import {CHARACTERS,EVIDENCE,CRISES,determineEnding,type Phase,type Tab,type Tone} from './story';
import {sfx,setAudio} from './audio';

const threshold=8;
export default function App(){
 const [phase,setPhase]=useState<Phase>('MENU'); const [tab,setTab]=useState<Tab>('dashboard'); const [audio,setAud]=useState(true);
 const [reviewed,setReviewed]=useState<string[]>([]); const [interviews,setInterviews]=useState<string[]>([]); const [trust,setTrust]=useState(2); const [crisis,setCrisis]=useState<string[]>([]); const [logs,setLogs]=useState<{text:string;tone:Tone}[]>([]); const [score,setScore]=useState(0); const [dialogue,setDialogue]=useState<{character:string;line:number}|null>(null);
 const [ending,setEnding]=useState<{id:string;title:string;summary:string}|null>(null); const [hours,setHours]=useState(48);
 const addLog=(text:string,tone:Tone='info')=>setLogs(v=>[{text,tone},...v].slice(0,8));
 const start=()=>{sfx('click');setPhase('TACTICAL');setTab('dashboard');addLog('CASE 01 INITIALIZED • 48-HOUR INVESTIGATION WINDOW OPEN.');};
 const inspect=(id:string)=>{if(!reviewed.includes(id)){setReviewed(v=>[...v,id]);setScore(v=>v+(EVIDENCE.find(e=>e.id===id)?.weight||1));addLog(`EVIDENCE REVIEWED • ${EVIDENCE.find(e=>e.id===id)?.title}`,'good');sfx('evidence')}else sfx('click');setTab('evidence')};
 const interview=(id:string)=>{if(!interviews.includes(id)){setInterviews(v=>[...v,id]);setScore(v=>v+1);setTrust(v=>Math.max(0,v-(id==='mamaEse'?0:1)));addLog(`INTERVIEW LOGGED • ${CHARACTERS.find(c=>c.id===id)?.name}`,'info');}setDialogue({character:id,line:0});sfx('click');};
 const resolve=(c:string,choice:string,effect:number,result:string)=>{if(crisis.includes(c))return;setCrisis(v=>[...v,c]);setScore(v=>v+effect);addLog(`${c.toUpperCase()} RESOLVED • ${result}`,effect>=2?'good':'warn'); if(choice==='nexus'){setTrust(v=>v-1);sfx('nexus')}else sfx(effect>=2?'good':'alert');};
 const finalUnlocked=reviewed.length>=threshold && interviews.length>=3 && crisis.length>=1;
 const decide=()=>{const e=determineEnding(score,trust);setEnding(e);setPhase('ENDING');sfx('finish');};
 const end=useMemo(()=>ending||determineEnding(score,trust),[ending,score,trust]);
 const currentDialogue=dialogue?CHARACTERS.find(c=>c.id===dialogue.character):undefined;
 return <div className="app">
  <div className="grain"/><header className="topline"><div className="brand">AFTERLIGHT <span>CASE 01 — THE REVIEW</span></div><div className="top-actions"><button className="icon-btn" onClick={()=>{setAud(v=>{setAudio(!v);return !v});sfx('click')}}>{audio?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><div className="case-pill">NIGHT OPS • 01</div></div></header>
  {phase==='MENU'&&<section className="menu-screen"><div className="menu-card"><div className="eyebrow">NIGERIAN INSTITUTIONAL PSYCHOLOGICAL THRILLER</div><h1>AFTERLIGHT</h1><div className="case-title">CASE 01 <b>THE REVIEW</b></div><p>Investigate sabotage, conflicting stories, and a system that may be learning more about you than you are learning about it.</p><div className="menu-actions"><button className="primary" onClick={start}><Play size={18} fill="currentColor"/> START CASE</button><button className="secondary" onClick={()=>{sfx('click');setPhase('HOWTO')}}>HOW TO PLAY</button></div><div className="menu-meta"><span>48 HOURS</span><span>•</span><span>5 PERSONNEL</span><span>•</span><span>9 EVIDENCE FILES</span></div></div></section>}
  {phase==='HOWTO'&&<section className="howto"><div className="panel wide"><div className="panel-head"><div><div className="eyebrow">OPERATIONS BRIEF</div><h2>HOW TO PLAY</h2></div><button className="icon-btn" onClick={()=>setPhase('MENU')}><X/></button></div><div className="how-grid"><div><h3>1 — INVESTIGATE</h3><p>Review evidence, identify contradictions, and interview the five key personnel.</p></div><div><h3>2 — SURVIVE THE CRISIS</h3><p>Operational choices change your score, your relationship with Nexus, and what becomes visible later.</p></div><div><h3>3 — QUESTION NEXUS</h3><p>Nexus is useful. It is also observing your decision patterns.</p></div><div><h3>4 — MAKE THE CALL</h3><p>Reach the investigation threshold, then commit to a final institutional decision.</p></div></div><button className="primary" onClick={()=>setPhase('MENU')}>RETURN TO CASE</button></div></section>}
  {phase==='TACTICAL'&&<section className="tactical"><div className="hud"><div><span className="status-dot"/> INVESTIGATION ACTIVE</div><div className="hud-stats"><span>TIME <b>{hours}H</b></span><span>EVIDENCE <b>{reviewed.length}/{threshold}</b></span><span>INTERVIEWS <b>{interviews.length}/3</b></span></div></div>
   <div className="layout"><aside className="sidebar"><div className="side-brand"><Gauge/><span>COMMAND</span></div>{([['dashboard','Command Dashboard',Gauge],['evidence','Evidence Archive',FileSearch],['personnel','Personnel',Users],['nexus','Nexus Interface',BrainCircuit],['crisis','Crisis Control',AlertTriangle],['final','Final Decision',ShieldCheck],['review','Board Review',Lock]] as [Tab,string,any][]).map(([id,label,Icon])=><button key={id} className={`nav ${tab===id?'active':''}`} onClick={()=>{setTab(id);sfx('click')}}><Icon size={16}/>{label}</button>)}<div className="side-log"><div className="eyebrow">LIVE LOG</div>{logs.length?logs.map((l,i)=><div className={`log ${l.tone}`} key={i}>{l.text}</div>):<div className="log">No event logged.</div>}</div></aside>
   <main className="main"><div className="hero-strip"><div><div className="eyebrow">AFTERLIGHT / FEDERAL RESPONSE CELL</div><h2>{tab==='dashboard'?'THE REVIEW':tab.toUpperCase()}</h2></div><div className="case-state"><span>CASE STATE</span><b>{crisis.length?'CRISIS CONTAINED':'PRIMARY INVESTIGATION'}</b></div></div>
   {tab==='dashboard'&&<Dashboard reviewed={reviewed.length} interviews={interviews.length} crisis={crisis.length} trust={trust} onEvidence={()=>setTab('evidence')} onPersonnel={()=>setTab('personnel')} onCrisis={()=>setTab('crisis')} />}
   {tab==='evidence'&&<Evidence reviewed={reviewed} onInspect={inspect}/>} 
   {tab==='personnel'&&<Personnel interviews={interviews} onInterview={interview} />}
   {tab==='nexus'&&<Nexus trust={trust} score={score} onQuestion={()=>{setTrust(v=>Math.max(0,v-1));addLog('NEXUS QUESTIONED • BEHAVIOUR MODEL UPDATED.','warn');sfx('nexus')}}/>}
   {tab==='crisis'&&<CrisisBoard crisis={crisis} onResolve={resolve}/>} 
   {tab==='final'&&<FinalDecision unlocked={finalUnlocked} reviewed={reviewed.length} interviews={interviews.length} crisis={crisis.length} onDecide={decide}/>} 
   {tab==='review'&&<BoardReview ending={ending||end} score={score} trust={trust} reviewed={reviewed.length} interviews={interviews.length} crisis={crisis.length}/>} 
   </main></div></section>}
  {phase==='ENDING'&&<section className="ending"><div className="ending-card"><div className="eyebrow">48-HOUR BOARD REVIEW COMPLETE</div><div className="ending-id">ENDING {end.id}</div><h1>{end.title}</h1><p>{end.summary}</p><div className="ending-grid"><div><span>EVIDENCE</span><b>{reviewed.length}</b></div><div><span>INTERVIEWS</span><b>{interviews.length}</b></div><div><span>CRISIS</span><b>{crisis.length}</b></div><div><span>NEXUS TRUST</span><b>{trust}</b></div></div><button className="primary" onClick={()=>window.location.reload()}>RESTART CASE</button></div></section>}
  {currentDialogue&&<div className="dialogue-backdrop" onClick={()=>setDialogue(null)}><div className="dialogue" onClick={e=>e.stopPropagation()}><div className="portrait">{currentDialogue.portrait}</div><div className="dialogue-main"><div className="dialogue-speaker"><div><div className="eyebrow">PERSONNEL INTERVIEW</div><h3>{currentDialogue.name}</h3><span>{currentDialogue.role}</span></div><button className="icon-btn" onClick={()=>setDialogue(null)}><X/></button></div><p>{currentDialogue.dialogue[dialogue.line].text}</p><div className="dialogue-actions"><button className="secondary" onClick={()=>setDialogue(null)}>CLOSE FILE</button>{dialogue.line+1<currentDialogue.dialogue.length&&<button className="primary" onClick={()=>setDialogue(v=>v?{...v,line:v.line+1}:v)}><ArrowRight size={16}/> CONTINUE</button>}</div></div></div></div>}
 </div>
}

function Dashboard(p:{reviewed:number;interviews:number;crisis:number;trust:number;onEvidence:()=>void;onPersonnel:()=>void;onCrisis:()=>void}){return <div className="dash-grid"><Card icon={<FileSearch/>} title="Evidence" value={`${p.reviewed}/${threshold}`} copy="Review the incident trail and find the missing pattern." action="OPEN ARCHIVE" onClick={p.onEvidence}/><Card icon={<Users/>} title="Personnel" value={`${p.interviews}/3`} copy="Five voices. Three interviews required before the final call." action="INTERVIEW" onClick={p.onPersonnel}/><Card icon={<AlertTriangle/>} title="Crisis" value={p.crisis?'RESOLVED':'LIVE'} copy="Operational choices will affect your investigation score." action="CRISIS CONTROL" onClick={p.onCrisis}/><div className="panel nexus-card"><div className="panel-icon"><BrainCircuit/></div><div className="eyebrow">NEXUS</div><h3>Adaptive Intelligence</h3><p>Trust state: <b>{p.trust}</b>. Nexus is now modeling your choices.</p><div className="mini-bar"><span style={{width:`${Math.min(100,Math.max(10,p.trust*33))}%`}}/></div></div><div className="panel wide-map"><div className="map-title"><div><div className="eyebrow">SECTOR MAP</div><h3>LAGOS • ABUJA • PORT HARCOURT</h3></div><Eye size={19}/></div><div className="map"><span className="node n1">IKEJA</span><span className="node n2">ABUJA</span><span className="node n3">PORT HARCOURT</span><i className="line l1"/><i className="line l2"/><i className="line l3"/></div></div></div>}
function Card(p:{icon:any;title:string;value:string;copy:string;action:string;onClick:()=>void}){return <div className="panel action-card"><div className="panel-icon">{p.icon}</div><div className="eyebrow">CASE MODULE</div><h3>{p.title}</h3><div className="metric">{p.value}</div><p>{p.copy}</p><button className="secondary small" onClick={()=>{sfx('click');p.onClick()}}>{p.action}<ArrowRight size={14}/></button></div>}
function Evidence({reviewed,onInspect}:{reviewed:string[];onInspect:(id:string)=>void}){return <div className="list-grid">{EVIDENCE.map(e=><article className={`panel evidence ${reviewed.includes(e.id)?'seen':''}`} key={e.id}><div className="evidence-top"><span className="evidence-code">EV-{e.id.slice(0,3).toUpperCase()}</span><span>{reviewed.includes(e.id)?'REVIEWED':'UNREVIEWED'}</span></div><h3>{e.title}</h3><p>{e.summary}</p><button className="secondary small" onClick={()=>onInspect(e.id)}>{reviewed.includes(e.id)?'REOPEN FILE':'INSPECT'} <ArrowRight size={14}/></button>{reviewed.includes(e.id)&&<div className="detail">{e.detail}</div>}</article>)}</div>}
function Personnel({interviews,onInterview}:{interviews:string[];onInterview:(id:string)=>void}){return <div className="people-grid">{CHARACTERS.map(c=><article className={`panel person ${interviews.includes(c.id)?'interviewed':''}`} key={c.id}><div className="portrait mini">{c.portrait}</div><div className="eyebrow">{c.origin}</div><h3>{c.name}</h3><p className="role">{c.role}</p><p>{c.tagline}</p><button className="secondary small" onClick={()=>onInterview(c.id)}>{interviews.includes(c.id)?'REVIEW INTERVIEW':'OPEN INTERVIEW'} <Mic2 size={14}/></button></article>)}</div>}
function Nexus({trust,score,onQuestion}:{trust:number;score:number;onQuestion:()=>void}){return <div className="nexus-layout"><div className="panel nexus-main"><div className="nexus-orb"><BrainCircuit size={44}/></div><div className="eyebrow">SYNTHETIC ADVISORY LAYER</div><h3>HELLO, INVESTIGATOR.</h3><p>Nexus has confidence in the current investigation model. That confidence is not the same as truth.</p><blockquote>“You are reviewing the crisis. I am reviewing your review.”</blockquote><button className="primary" onClick={onQuestion}>QUESTION NEXUS</button></div><div className="panel"><div className="eyebrow">CURRENT MODEL</div><div className="nexus-stat"><span>Trust</span><b>{trust}</b></div><div className="nexus-stat"><span>Case score</span><b>{score}</b></div><div className="nexus-stat"><span>Observation</span><b>ACTIVE</b></div></div></div>}
function CrisisBoard({crisis,onResolve}:{crisis:string[];onResolve:(c:string,o:string,e:number,r:string)=>void}){return <div className="crisis-grid">{CRISES.map(c=><article className={`panel crisis ${crisis.includes(c.id)?'resolved':''}`} key={c.id}><div className="eyebrow">{c.location}</div><h3>{c.title}</h3><p>{c.summary}</p>{crisis.includes(c.id)?<div className="resolved-badge"><ShieldCheck size={16}/> CRISIS RESOLVED</div>:<div className="choices">{c.options.map(o=><button key={o.id} className="secondary choice" onClick={()=>onResolve(c.id,o.id,o.effect,o.result)}><span>{o.label}</span><ArrowRight size={14}/></button>)}</div>}</article>)}</div>}
function FinalDecision({unlocked,reviewed,interviews,crisis,onDecide}:{unlocked:boolean;reviewed:number;interviews:number;crisis:number;onDecide:()=>void}){return <div className="panel final-panel"><div className="eyebrow">DECISION GATE</div><h3>Commit to your institutional response.</h3><p>The case should not end until the evidence chain is materially complete.</p><div className="gate"><div>Evidence <b>{reviewed}/{threshold}</b></div><div>Interviews <b>{interviews}/3</b></div><div>Crisis <b>{crisis}/1+</b></div></div><button className="primary" disabled={!unlocked} onClick={onDecide}>{unlocked?'ISSUE FINAL DECISION':'LOCKED — CONTINUE INVESTIGATION'}</button></div>}
function BoardReview({ending,score,trust,reviewed,interviews,crisis}:{ending:{id:string;title:string;summary:string};score:number;trust:number;reviewed:number;interviews:number;crisis:number}){return <div className="review-grid"><div className="panel"><div className="eyebrow">BOARD OUTCOME</div><div className="ending-id">ENDING {ending.id}</div><h3>{ending.title}</h3><p>{ending.summary}</p></div><div className="panel"><div className="eyebrow">AUDIT SNAPSHOT</div>{[['Evidence reviewed',reviewed],['Interviews',interviews],['Crisis events',crisis],['Investigation score',score],['Nexus trust',trust]].map(([k,v])=><div className="snapshot" key={String(k)}><span>{k}</span><b>{v}</b></div>)}</div></div>}
